packages:
  - "apps/*"
  - "packages/*"

catalog:
  # React (admin, web)
  react: ^19.0.4
  react-dom: ^19.0.4
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3

  # Hono (admin, web)
  hono: ^4.11.7
  "@hono/valibot-validator": ^0.6.1

  # TanStack (admin, web)
  "@tanstack/react-query": ^5.90.20
  "@tanstack/react-router": ^1.157.16

  # Validation (admin, web, shared)
  valibot: ^1.2.0

  # Database (admin, web, db)
  drizzle-orm: ^0.45.1

  # UI (admin, web)
  lucide-react: ^0.563.0
  tailwindcss: ^4.1.18

  # Build (admin, web)
  vite: ^7.3.1
  "@vitejs/plugin-react": ^5.1.2
