/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'
import { Route as RecIdRouteImport } from './routes/rec.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/tracks/$id',
  path: '/tracks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecIdRoute = RecIdRouteImport.update({
  id: '/rec/$id',
  path: '/rec/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rec/$id': typeof RecIdRoute
  '/tracks/$id': typeof TracksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rec/$id': typeof RecIdRoute
  '/tracks/$id': typeof TracksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rec/$id': typeof RecIdRoute
  '/tracks/$id': typeof TracksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rec/$id' | '/tracks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rec/$id' | '/tracks/$id'
  id: '__root__' | '/' | '/rec/$id' | '/tracks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecIdRoute: typeof RecIdRoute
  TracksIdRoute: typeof TracksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/tracks/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec/$id': {
      id: '/rec/$id'
      path: '/rec/$id'
      fullPath: '/rec/$id'
      preLoaderRoute: typeof RecIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecIdRoute: RecIdRoute,
  TracksIdRoute: TracksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
